---
# https://taskfile.dev

version: '3'

set:
  - nounset
  - errexit
  - pipefail

silent: true

# This sets the watch interval to .5s; https://taskfile.dev/usage/#watch-tasks
interval: '500ms'

tasks:
  lock:
    desc: Generate a Pipfile.lock if Pipfile changed from last run
    internal: true
    sources:
      - Pipfile
    generates:
      - Pipfile.lock
    cmds:
      - pipenv lock

  init-pipenv:
    desc: Initializes the pipenv virtual environment if Pipfile.lock changes
    internal: true
    sources:
      - Pipfile.lock
    cmds:
      - pipenv install --deploy --ignore-pipfile --dev

  runner-apt-install:
    desc: Install something on a GitHub Actions runner via apt
    internal: true
    status:
      - '{{if eq .GITHUB_ACTIONS "true"}}exit 1{{end}}'
    requires:
      vars: [TOOLS]
    preconditions:
      - sudo apt-get update
    platforms: [linux]
    cmds:
      - for:
          var: TOOLS
          split: ','
          as: tool
        cmd: apt-get install -y --no-install-recommends {{.tool}}

  mac-brew-install:
    desc: Install something on a mac via brew
    internal: true
    platforms: [darwin]
    requires:
      vars: [TOOLS]
    cmds:
      - for:
          var: TOOLS
          split: ','
          as: tool
        cmd: brew install {{.tool}}

  init-install-tools:
    desc: Install required tools
    internal: true
    cmds:
      - task: runner-apt-install
        vars:
          TOOLS: xclip

  init:
    desc: Initialize the repo for local use; intended to be run after git clone
    deps: [lock]
    cmds:
      - task: init-pipenv
      - task: init-install-tools
      - pipenv run playwright install --with-deps chromium

  build:
    desc: Build the project
    # Sources are needed for auto-rebuilding via the taskfile watch feature
    sources:
      - docs/**/*.md
      - docs/**/*.py
      - docs/**/*.rst
    cmds:
      - pipenv run sphinx-build -b html docs build

  open:
    desc: Open the home page
    deps: [build]
    cmds:
      - open {{.ROOT_DIR}}/build/index.html

  test:
    desc: Run the project tests
    deps: [clean, build]
    # Tests only work locally for now
    platforms: [darwin]
    env:
      LOG_LEVEL: '{{ .CLI_ARGS | default "INFO" }}'
      NUMBER_OF_LABS:
        sh: find tests/ -name '*.md' | wc -l
    cmds:
      - pipenv run pytest -n "${NUMBER_OF_LABS}" -v tests/ --log-cli-level "${LOG_LEVEL}"

  destroy:
    desc: Run terraform destroys and cleanup all of the test terraform modules
    cmds:
      - |
        for dir in $(find tests -type d -maxdepth 1 -mindepth 1); do
          pushd "${dir}" >/dev/null
          echo "Running destroy in ${dir}..."
          terraform destroy -auto-approve
          popd >/dev/null
        done

  update:
    desc: Update the project dev and runtime dependencies, and other misc components
    cmds:
      - pipenv update

  clean:
    desc: Clean up build artifacts, cache files/directories, temp files, etc.
    cmds:
      - rm -rf {{.ROOT_DIR}}/build/
      - find {{.ROOT_DIR}} -type d -name '.mypy_cache' -exec rm -rf {} +
      - find {{.ROOT_DIR}} -type d -name '.pytest_cache' -exec rm -rf {} +
      - find {{.ROOT_DIR}} -type d -name '.ruff_cache' -exec rm -rf {} +
      - find {{.ROOT_DIR}} -type d -name '.task' -exec rm -rf {} +
      - find {{.ROOT_DIR}} -type d -name '__pycache__' -exec rm -rf {} +
      - find {{.ROOT_DIR}} -type d -name 'coverage-reports' -exec rm -rf {} +
      - find {{.ROOT_DIR}} -type f -name '*.pyc' -delete
      - find {{.ROOT_DIR}} -type f -name '.DS_Store' -delete
      - find {{.ROOT_DIR}} -type f -name '.Thumbs.db' -delete
      - find {{.ROOT_DIR}} -type f -name '.coverage' -delete
