---
name: Deploy to GitHub Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

env:
  python_version: "3.11"

defaults:
  run:
    shell: 'bash --noprofile --norc -Eeuo pipefail {0}'

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # Needed to generate last modified dates
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ env.python_version }}
      - uses: actions/cache@v4
        with:
          path: ~/.local/share/virtualenvs
          key: ${{ runner.os }}-python-${{ env.python_version }}-pipenv-${{ hashFiles('Pipfile.lock') }}
      - name: Install the dependencies
        run: python -m pip install --upgrade pipenv
      - name: Install Task
        uses: arduino/setup-task@v2
      - name: Initialize the repository
        run: task -v init
      - name: Generate the HTML
        run: task -v build
      - name: Configure AWS Credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::728412089767:role/jonzeolla.com_lab_testing
          aws-region: us-east-1
      - name: Run the tests
        run: task -v test
      - name: Cleanup from testing (just in case)
        run: task -v destroy
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './build'
  deploy:
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      pages: write
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
