---
name: Test

on: pull_request

defaults:
  run:
    shell: 'bash --noprofile --norc -Eeuo pipefail {0}'

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v2
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"
      - name: Set up Python
        run: uv python install
      - name: Install Task
        uses: arduino/setup-task@v2
      - name: Initialize the repository
        run: task -v init
      - name: Generate the HTML
        run: task -v build
      - name: Configure AWS Credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::728412089767:role/jonzeolla.com_lab_testing
          aws-region: us-east-1
      - name: Test the project
        run: task -v test
      - name: Cleanup from testing (just in case)
        run: task -v destroy
