---
name: Testing CI

on:
  push:

env:
  python_version: "3.10"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          # Needed to generate last modified dates
          fetch-depth: 0
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ env.python_version }}
      - uses: actions/cache@v3
        with:
          path: ~/.local/share/virtualenvs
          key: ${{ runner.os }}-python-${{ env.python_version }}-pipenv-${{ hashFiles('Pipfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-python-${{ env.python_version }}-pipenv-
            ${{ runner.os }}-python-
      - name: Install Task
        uses: arduino/setup-task@v1
      - name: Initialize the repository
        run: |
          python -m pip install --upgrade pipenv
          task init
      - name: Generate the HTML
        run: task build
      - name: Run the tests
        run: task test
