---
name: Update

on:
  schedule:
    - cron: '23 0 * * 6'
  workflow_dispatch:

env:
  python_version: "3.10"

jobs:
  update:
    name: Update
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ env.python_version }}
      - uses: actions/cache@v3
        with:
          path: ~/.local/share/virtualenvs
          key: ${{ runner.os }}-python-${{ env.python_version }}-pipenv-${{ hashFiles('Pipfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-python-${{ env.python_version }}-pipenv-
            ${{ runner.os }}-python-
      - name: Install Task
        uses: arduino/setup-task@v1
      - name: Initialize the repository
        run: |
          python -m pip install --upgrade pipenv
          task init
      - name: Update the repository
        run: task update
      - name: Create or update a pull request
        uses: peter-evans/create-pull-request@v4
        with:
          title: Automated update
          commit-message: Automated update
          committer: Automation <automation@jonzeolla.com>
          delete-branch: true
          signoff: true
