---
name: Update

on:
  schedule:
    - cron: '23 0 * * 6'
  workflow_dispatch:

defaults:
  run:
    shell: 'bash --noprofile --norc -Eeuo pipefail {0}'

jobs:
  update:
    name: Update
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v2
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"
      - name: Set up Python
        run: uv python install
      - name: Install Task
        uses: arduino/setup-task@v2
      - name: Initialize the repository
        run: task -v init
      - name: Update the repository
        run: task -v update
      - name: Create or update a pull request
        uses: peter-evans/create-pull-request@v6
        with:
          title: Automated update
          commit-message: Automated update
          committer: Automation <automation@jonzeolla.com>
          delete-branch: true
          signoff: true
